// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: lnd/lnd.proto

package lnd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status_Value int32

const (
	Status_FAILED  Status_Value = 0
	Status_RUNNING Status_Value = 1
)

// Enum value maps for Status_Value.
var (
	Status_Value_name = map[int32]string{
		0: "FAILED",
		1: "RUNNING",
	}
	Status_Value_value = map[string]int32{
		"FAILED":  0,
		"RUNNING": 1,
	}
)

func (x Status_Value) Enum() *Status_Value {
	p := new(Status_Value)
	*p = x
	return p
}

func (x Status_Value) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_Value) Descriptor() protoreflect.EnumDescriptor {
	return file_lnd_lnd_proto_enumTypes[0].Descriptor()
}

func (Status_Value) Type() protoreflect.EnumType {
	return &file_lnd_lnd_proto_enumTypes[0]
}

func (x Status_Value) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_Value.Descriptor instead.
func (Status_Value) EnumDescriptor() ([]byte, []int) {
	return file_lnd_lnd_proto_rawDescGZIP(), []int{1, 0}
}

type NodeDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nodename string       `protobuf:"bytes,2,opt,name=Nodename,proto3" json:"Nodename,omitempty"`
	IP       string       `protobuf:"bytes,3,opt,name=IP,proto3" json:"IP,omitempty"`
	UserId   string       `protobuf:"bytes,4,opt,name=UserId,proto3" json:"UserId,omitempty"`
	CreateAt string       `protobuf:"bytes,5,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	Status   Status_Value `protobuf:"varint,6,opt,name=status,proto3,enum=Status_Value" json:"status,omitempty"`
}

func (x *NodeDetail) Reset() {
	*x = NodeDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lnd_lnd_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDetail) ProtoMessage() {}

func (x *NodeDetail) ProtoReflect() protoreflect.Message {
	mi := &file_lnd_lnd_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDetail.ProtoReflect.Descriptor instead.
func (*NodeDetail) Descriptor() ([]byte, []int) {
	return file_lnd_lnd_proto_rawDescGZIP(), []int{0}
}

func (x *NodeDetail) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeDetail) GetNodename() string {
	if x != nil {
		return x.Nodename
	}
	return ""
}

func (x *NodeDetail) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *NodeDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *NodeDetail) GetCreateAt() string {
	if x != nil {
		return x.CreateAt
	}
	return ""
}

func (x *NodeDetail) GetStatus() Status_Value {
	if x != nil {
		return x.Status
	}
	return Status_FAILED
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value Status_Value `protobuf:"varint,1,opt,name=value,proto3,enum=Status_Value" json:"value,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lnd_lnd_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_lnd_lnd_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_lnd_lnd_proto_rawDescGZIP(), []int{1}
}

func (x *Status) GetValue() Status_Value {
	if x != nil {
		return x.Value
	}
	return Status_FAILED
}

type NodeList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeDetail `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lnd_lnd_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_lnd_lnd_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_lnd_lnd_proto_rawDescGZIP(), []int{2}
}

func (x *NodeList) GetNodes() []*NodeDetail {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NodeId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int32 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *NodeId) Reset() {
	*x = NodeId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lnd_lnd_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeId) ProtoMessage() {}

func (x *NodeId) ProtoReflect() protoreflect.Message {
	mi := &file_lnd_lnd_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeId.ProtoReflect.Descriptor instead.
func (*NodeId) Descriptor() ([]byte, []int) {
	return file_lnd_lnd_proto_rawDescGZIP(), []int{3}
}

func (x *NodeId) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_lnd_lnd_proto protoreflect.FileDescriptor

var file_lnd_lnd_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x6e, 0x64, 0x2f, 0x6c, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xa3, 0x01, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x25,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x4f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x23, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x55, 0x4e,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x22, 0x2d, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05,
	0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x84, 0x01, 0x0a, 0x03, 0x4c, 0x4e, 0x44, 0x12, 0x28, 0x0a,
	0x0a, 0x53, 0x70, 0x61, 0x77, 0x6e, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x0b, 0x2e, 0x4e, 0x6f,
	0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x1a, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x12, 0x2c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4e, 0x6f,
	0x64, 0x65, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x07, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x1a, 0x0b, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x65, 0x73, 0x61,
	0x66, 0x65, 0x72, 0x6f, 0x6f, 0x74, 0x2f, 0x67, 0x70, 0x72, 0x63, 0x2d, 0x6c, 0x6e, 0x64, 0x3b,
	0x6c, 0x6e, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lnd_lnd_proto_rawDescOnce sync.Once
	file_lnd_lnd_proto_rawDescData = file_lnd_lnd_proto_rawDesc
)

func file_lnd_lnd_proto_rawDescGZIP() []byte {
	file_lnd_lnd_proto_rawDescOnce.Do(func() {
		file_lnd_lnd_proto_rawDescData = protoimpl.X.CompressGZIP(file_lnd_lnd_proto_rawDescData)
	})
	return file_lnd_lnd_proto_rawDescData
}

var file_lnd_lnd_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lnd_lnd_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lnd_lnd_proto_goTypes = []interface{}{
	(Status_Value)(0),  // 0: Status.Value
	(*NodeDetail)(nil), // 1: NodeDetail
	(*Status)(nil),     // 2: Status
	(*NodeList)(nil),   // 3: NodeList
	(*NodeId)(nil),     // 4: NodeId
}
var file_lnd_lnd_proto_depIdxs = []int32{
	0, // 0: NodeDetail.status:type_name -> Status.Value
	0, // 1: Status.value:type_name -> Status.Value
	1, // 2: NodeList.nodes:type_name -> NodeDetail
	1, // 3: LND.SpawnNodes:input_type -> NodeDetail
	2, // 4: LND.GetNodesListByStatus:input_type -> Status
	4, // 5: LND.DestroyNode:input_type -> NodeId
	3, // 6: LND.SpawnNodes:output_type -> NodeList
	3, // 7: LND.GetNodesListByStatus:output_type -> NodeList
	1, // 8: LND.DestroyNode:output_type -> NodeDetail
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_lnd_lnd_proto_init() }
func file_lnd_lnd_proto_init() {
	if File_lnd_lnd_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lnd_lnd_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lnd_lnd_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lnd_lnd_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lnd_lnd_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lnd_lnd_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lnd_lnd_proto_goTypes,
		DependencyIndexes: file_lnd_lnd_proto_depIdxs,
		EnumInfos:         file_lnd_lnd_proto_enumTypes,
		MessageInfos:      file_lnd_lnd_proto_msgTypes,
	}.Build()
	File_lnd_lnd_proto = out.File
	file_lnd_lnd_proto_rawDesc = nil
	file_lnd_lnd_proto_goTypes = nil
	file_lnd_lnd_proto_depIdxs = nil
}
